<a href="https://colab.research.google.com/github/oswram19/etl-data-pipline-1764382012/blob/main/notebook/login.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import re

In [8]:
url ="https://raw.githubusercontent.com/oswram19/etl-data-pipline-1764382012/refs/heads/main/data/G_login.csv"
df = pd.read_csv(url)

df.head()

  id_login id_usuario          fecha_login              ip
0   LG6000      US414  2024/08/22 05:00:00  192.168.18.198
1   LG6001      US418  2024-02-03 10:00:00   192.168.1.214
2   LG6002      US476  2024-01-11 21:00:00   192.168.20.28
3   LG6003      US449  2024-06-13 18:00:00  192.168.12.135
4   LG6004      US422  2024-08-26 00:00:00   192.168.11.22

In [7]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 236 entries, 0 to 235
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_login     236 non-null    object
 1   id_usuario   228 non-null    object
 2   fecha_login  229 non-null    object
 3   ip           233 non-null    object
dtypes: object(4)
memory usage: 7.5+ KB

id_login       0
id_usuario     8
fecha_login    7
ip             3
dtype: int64

In [11]:
print('Shape before cleaning:', df.shape)


df.dropna(subset=['id_usuario', 'ip'], inplace=True)

df['fecha_login'] = pd.to_datetime(df['fecha_login'], errors='coerce')

df['fecha_login'].fillna(method='ffill', inplace=True)

print('Shape after cleaning:', df.shape)
print('\nNull values after cleaning:')
print(df.isnull().sum())

df.head()

Shape before cleaning: (225, 4)
Shape after cleaning: (225, 4)

Null values after cleaning:
id_login       0
id_usuario     0
fecha_login    0
ip             0
dtype: int64

/tmp/ipykernel_4015/4211899599.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['fecha_login'].fillna(method='ffill', inplace=True)
/tmp/ipykernel_4015/4211899599.py:10: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['fecha_login'].fillna(method='ffill', inplace=True)

  id_login id_usuario         fecha_login              ip
0   LG6000      US414 2024-08-22 05:00:00  192.168.18.198
1   LG6001      US418 2024-08-22 05:00:00   192.168.1.214
2   LG6002      US476 2024-08-22 05:00:00   192.168.20.28
3   LG6003      US449 2024-08-22 05:00:00  192.168.12.135
4   LG6004      US422 2024-08-22 05:00:00   192.168.11.22

In [13]:
# extraer horas dias , meses , años
df['login_hour'] = df['fecha_login'].dt.hour
df['login_day'] = df['fecha_login'].dt.day
df['login_month'] = df['fecha_login'].dt.month
df['login_year'] = df['fecha_login'].dt.year

print('DataFrame after extracting time features:')
display(df.head())

DataFrame after extracting time features:

,id_login,id_usuario,fecha_login,ip,login_hour,login_day,login_month,login_year
0,LG6000,US414,2024-08-22 05:00:00,192.168.18.198,5,22,8,2024
1,LG6001,US418,2024-08-22 05:00:00,192.168.1.214,5,22,8,2024
2,LG6002,US476,2024-08-22 05:00:00,192.168.20.28,5,22,8,2024
3,LG6003,US449,2024-08-22 05:00:00,192.168.12.135,5,22,8,2024
4,LG6004,US422,2024-08-22 05:00:00,192.168.11.22,5,22,8,2024

In [15]:
# Expresion regulares ipv4
ip_pattern = r'^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'

#se crea una nueva columna is_valid_ip
df['is_valid_ip'] = df['ip'].apply(lambda x: bool(re.match(ip_pattern, str(x))))

# separar los curados (valid IPs) y rejects (invalid IPs) DataFrames
df_curated = df[df['is_valid_ip']].copy()
df_rejects = df[~df['is_valid_ip']].copy()

print('Curated DataFrame (Valid IPs) - first 5 rows:')
display(df_curated.head())

print('\nRejects DataFrame (Invalid IPs) - first 5 rows:')
display(df_rejects.head())

print(f'\nShape of Curated DataFrame: {df_curated.shape}')
print(f'Shape of Rejects DataFrame: {df_rejects.shape}')

Curated DataFrame (Valid IPs) - first 5 rows:

,id_login,id_usuario,fecha_login,ip,login_hour,login_day,login_month,login_year,is_valid_ip
0,LG6000,US414,2024-08-22 05:00:00,192.168.18.198,5,22,8,2024,True
1,LG6001,US418,2024-08-22 05:00:00,192.168.1.214,5,22,8,2024,True
2,LG6002,US476,2024-08-22 05:00:00,192.168.20.28,5,22,8,2024,True
3,LG6003,US449,2024-08-22 05:00:00,192.168.12.135,5,22,8,2024,True
4,LG6004,US422,2024-08-22 05:00:00,192.168.11.22,5,22,8,2024,True

Rejects DataFrame (Invalid IPs) - first 5 rows:

,id_login,id_usuario,fecha_login,ip,login_hour,login_day,login_month,login_year,is_valid_ip
11,LG6011,US410,2024-09-30 00:00:00,ip_desconocida,0,30,9,2024,False
15,LG6015,US409,2024-09-30 00:00:00,ip_desconocida,0,30,9,2024,False
49,LG6049,US486,2024-10-18 22:00:00,999.999.1.1,22,18,10,2024,False
73,LG6073,US428,2024-09-09 13:00:00,ip_desconocida,13,9,9,2024,False
114,LG6114,US519,2024-09-09 13:00:00,999.999.1.1,13,9,9,2024,False

Shape of Curated DataFrame: (216, 9)
Shape of Rejects DataFrame: (9, 9)

guardar los archivos curated y rejects

In [21]:
df_curated.to_csv('login_curated.csv', index=False)
print("guardar g_login_curated.csv")

df_rejects.to_csv('login_rejects.csv', index=False)
print("guardado g_rejects.csv")

guardar g_login_curated.csv
guardado g_rejects.csv

LIBRERIA DE POSTGRESQL

In [27]:
pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

In [28]:
from sqlalchemy import create_engine

db_connection_str = "postgresql://etl_seguros_gs5p_user:mlggyX4FmZphFrbO1p9v1Amxiu2bIkMO@dpg-d6qu59fkijhs73bcuo0g-a.oregon-postgres.render.com/etl_seguros_gs5p"

# CREACION DATABASE
engine = create_engine(db_connection_str)

try:

    df_curated.to_sql('login_curated', engine, if_exists='replace', index=False)
    print("df_curated successfully uploaded to 'login_curated' table.")


    df_rejects.to_sql('login_rejects', engine, if_exists='replace', index=False)
    print("df_rejects successfully uploaded to 'login_rejects' table.")

except Exception as e:
    print(f"An error occurred: {e}")
finally:

    engine.dispose()

df_curated successfully uploaded to 'login_curated' table.
df_rejects successfully uploaded to 'login_rejects' table.