<a href="https://colab.research.google.com/github/oswram19/etl-data-pipline-1764382012/blob/main/notebooks/actividad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import re

In [7]:
url ="https://raw.githubusercontent.com/oswram19/etl-data-pipline-1764382012/refs/heads/main/data/G_actividad.csv"
df = pd.read_csv(url)

df.head()

  id_actividad id_usuario             accion      fecha_actividad      modulo
0      ACT9000      US518  actualizar pedido  2024-05-20 07:00:00   seguridad
1      ACT9001      US512      cambio clave   2024-11-02 12:00:00    reportes
2      ACT9002      US450             logout  2024-08-29 19:00:00    usuarios
3      ACT9003      US467           consulta  2024-04-16 14:00:00   seguridad
4      ACT9004      US420           consulta  2024-08-08 05:00:00  inventario

In [6]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 240 entries, 0 to 245
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_actividad     240 non-null    object
 1   id_usuario       240 non-null    object
 2   accion           240 non-null    object
 3   fecha_actividad  240 non-null    object
 4   modulo           240 non-null    object
dtypes: object(5)
memory usage: 11.2+ KB

id_actividad       0
id_usuario         0
accion             0
fecha_actividad    0
modulo             0
dtype: int64

LIMPIAR DATOS

In [ ]:
df['fecha_actividad'] = pd.to_datetime(df['fecha_actividad'], errors='coerce')
display(df.head())

In [5]:
df['id_usuario'].fillna('Unknown', inplace=True)
df.dropna(subset=['fecha_actividad'], inplace=True)

print('Missing values after cleaning:')
display(df.isnull().sum())

print('DataFrame information after cleaning:')
display(df.info())

Missing values after cleaning:

/tmp/ipykernel_35967/1575805141.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['id_usuario'].fillna('Unknown', inplace=True)

id_actividad       0
id_usuario         0
accion             0
fecha_actividad    0
modulo             0
dtype: int64

DataFrame information after cleaning:
<class 'pandas.core.frame.DataFrame'>
Index: 240 entries, 0 to 245
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_actividad     240 non-null    object
 1   id_usuario       240 non-null    object
 2   accion           240 non-null    object
 3   fecha_actividad  240 non-null    object
 4   modulo           240 non-null    object
dtypes: object(5)
memory usage: 11.2+ KB

None

In [10]:
df_encoded = pd.get_dummies(df, columns=['accion', 'modulo'], prefix=['accion', 'modulo'])

display(df_encoded.head())

print('\nDimensiones del DataFrame Curado:', df_encoded.shape)
print('Nnueva columna creada:', [col for col in df_encoded.columns if col.startswith('accion_') or col.startswith('modulo_')])

,id_actividad,id_usuario,fecha_actividad,accion_ actualizar pedido,accion_ crear pedido,accion_ login,accion_ logout,accion_actualizar pedido,accion_anular pedido,accion_anular pedido,...,accion_consulta,accion_crear pedido,accion_login,accion_login,accion_logout,modulo_inventario,modulo_reportes,modulo_seguridad,modulo_usuarios,modulo_ventas
0,ACT9000,US518,2024-05-20 07:00:00,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
1,ACT9001,US512,2024-11-02 12:00:00,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
2,ACT9002,US450,2024-08-29 19:00:00,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
3,ACT9003,US467,2024-04-16 14:00:00,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
4,ACT9004,US420,2024-08-08 05:00:00,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False

Dimensiones del DataFrame Curado: (246, 23)
Nnueva columna creada: ['accion_ actualizar pedido ', 'accion_ crear pedido ', 'accion_ login ', 'accion_ logout ', 'accion_actualizar pedido', 'accion_anular pedido', 'accion_anular pedido ', 'accion_cambio clave', 'accion_cambio clave ', 'accion_consulta', 'accion_consulta ', 'accion_crear pedido', 'accion_login', 'accion_login ', 'accion_logout', 'modulo_inventario', 'modulo_reportes', 'modulo_seguridad', 'modulo_usuarios', 'modulo_ventas']

In [11]:
print('Información del DataFrame después de la codificación one-hot:')
display(df_encoded.info())

print('Valores faltantes después de la codificación one-hot:')
display(df_encoded.isnull().sum())

Información del DataFrame después de la codificación one-hot:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id_actividad                246 non-null    object
 1   id_usuario                  238 non-null    object
 2   fecha_actividad             240 non-null    object
 3   accion_ actualizar pedido   246 non-null    bool
 4   accion_ crear pedido        246 non-null    bool
 5   accion_ login               246 non-null    bool
 6   accion_ logout              246 non-null    bool
 7   accion_actualizar pedido    246 non-null    bool
 8   accion_anular pedido        246 non-null    bool
 9   accion_anular pedido        246 non-null    bool
 10  accion_cambio clave         246 non-null    bool
 11  accion_cambio clave         246 non-null    bool
 12  accion_consulta             246 non-null    bool
 13  accion_consulta             246 non-null    bool
 14  accion_crear pedido         246 non-null    bool
 15  accion_login                246 non-null    bool
 16  accion_login                246 non-null    bool
 17  accion_logout               246 non-null    bool
 18  modulo_inventario           246 non-null    bool
 19  modulo_reportes             246 non-null    bool
 20  modulo_seguridad            246 non-null    bool
 21  modulo_usuarios             246 non-null    bool
 22  modulo_ventas               246 non-null    bool
dtypes: bool(20), object(3)
memory usage: 10.7+ KB

None

Valores faltantes después de la codificación one-hot:

id_actividad                  0
id_usuario                    8
fecha_actividad               6
accion_ actualizar pedido     0
accion_ crear pedido          0
accion_ login                 0
accion_ logout                0
accion_actualizar pedido      0
accion_anular pedido          0
accion_anular pedido          0
accion_cambio clave           0
accion_cambio clave           0
accion_consulta               0
accion_consulta               0
accion_crear pedido           0
accion_login                  0
accion_login                  0
accion_logout                 0
modulo_inventario             0
modulo_reportes               0
modulo_seguridad              0
modulo_usuarios               0
modulo_ventas                 0
dtype: int64

Separando Datos Curados y Rechazados

In [12]:
# Regenerar df_encoded a partir del 'df' actual para asegurar la consistencia
# El 'df' actual ya ha manejado los valores faltantes en 'fecha_actividad' e 'id_usuario'
df_encoded = pd.get_dummies(df, columns=['accion', 'modulo'], prefix=['accion', 'modulo'])

print('Dimensiones del DataFrame Curado (regenerado):', df_encoded.shape)
display(df_encoded.head())

Dimensiones del DataFrame Curado (regenerado): (246, 23)

,id_actividad,id_usuario,fecha_actividad,accion_ actualizar pedido,accion_ crear pedido,accion_ login,accion_ logout,accion_actualizar pedido,accion_anular pedido,accion_anular pedido,...,accion_consulta,accion_crear pedido,accion_login,accion_login,accion_logout,modulo_inventario,modulo_reportes,modulo_seguridad,modulo_usuarios,modulo_ventas
0,ACT9000,US518,2024-05-20 07:00:00,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
1,ACT9001,US512,2024-11-02 12:00:00,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
2,ACT9002,US450,2024-08-29 19:00:00,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
3,ACT9003,US467,2024-04-16 14:00:00,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
4,ACT9004,US420,2024-08-08 05:00:00,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False

In [13]:
# Cargar el CSV original para identificar las filas rechazadas
original_df = pd.read_csv(url)

# Convertir 'fecha_actividad' con errors='coerce' para identificar fechas inválidas
original_df['fecha_actividad_temp'] = pd.to_datetime(original_df['fecha_actividad'], errors='coerce')

# Identificar filas donde 'fecha_actividad' era inválida (filas rechazadas)
rejected_df = original_df[original_df['fecha_actividad_temp'].isna()].drop(columns=['fecha_actividad_temp'])

print('\nDimensiones de los Datos Rechazados:', rejected_df.shape)
display(rejected_df.head())

# Eliminar la columna temporal de original_df si no se necesita más tarde
del original_df['fecha_actividad_temp']

Dimensiones de los Datos Rechazados: (16, 5)

   id_actividad id_usuario         accion      fecha_actividad     modulo
15      ACT9015      US447   crear pedido           31/15/2024   usuarios
29      ACT9029      US491   crear pedido           2025/99/10   usuarios
40      ACT9040      US460  anular pedido  2024/08/21 14:00:00  seguridad
55      ACT9055      US426          login  2024/08/29 16:00:00  seguridad
65      ACT9065      US504  anular pedido  2024/08/26 14:00:00  seguridad

In [15]:
# Guardar los datos curados
df_encoded.to_csv('actividad_curated.csv', index=False)
print('Datos curados guardados en curated_data.csv')

# Guardar los datos rechazados
rejected_df.to_csv('actividad_rejected.csv', index=False)
print('Datos rechazados guardados en rejected_data.csv')

print('\nSeparación y guardado completados!')

Datos curados guardados en curated_data.csv
Datos rechazados guardados en rejected_data.csv

Separación y guardado completados!

In [16]:
from sqlalchemy import create_engine

# URL de conexión a la base de datos PostgreSQL
db_connection_str = 'postgresql://etl_seguros_gs5p_user:mlggyX4FmZphFrbO1p9v1Amxiu2bIkMO@dpg-d6qu59fkijhs73bcuo0g-a.oregon-postgres.render.com/etl_seguros_gs5p'

# Crear el motor de la base de datos
engine = create_engine(db_connection_str)

try:
    # Cargar el DataFrame a PostgreSQL
    # if_exists='replace' reemplazará la tabla si ya existe
    # index=False evita escribir el índice del DataFrame como una columna
    df_encoded.to_sql('actividad_curated_db', engine, if_exists='replace', index=False)
    print('Datos cargados exitosamente en la tabla actividad_curated_db de PostgreSQL.')
except Exception as e:
    print(f'Error al cargar los datos a PostgreSQL: {e}')

Datos cargados exitosamente en la tabla actividad_curated_db de PostgreSQL.